### PR TITLE
Codebase cleanup

### PR DESCRIPTION
**Pull request by derenv**
* Codebase now linted with gjs styleguide
* Added eslint:recommended+jsdoc rulesets to linting
* SPDX licensing added, compliant with v3.0 of the specification
* General directory layout cleaned up
* Multiple housekeeping refactors (partly to meet styleguides)
* Gnome shell 41 compatibility flag added

### CODE REVIEW

**Comment by derenv** [comment]
@kenohassler I think once this is merged we should focus on creating the v9.0 release - it's loooong overdue.

**Comment by kenohassler** [comment]
Yep, we should (optimally, before Ubuntu 22.04 comes out and breaks the old version). I think we did enough housekeeping work :stuck_out_tongue:
Is there anything missing feature-wise for v9?

**Comment by derenv** [comment]
I think we're good! we'll need @ethanwharris to approve the changes and update the [gnome extensions page](https://extensions.gnome.org/extension/1320/nvidia-gpu-stats-tool/).

**Comment by kenohassler** [comment]
I don't think the zip should be in-tree, it should be added as a binary file when creating the GitHub Release (I guess Ethan has to do this). And you can't just CC0 the whole thing btw :grin:

**Review by ethanwharris — APPROVED** [review]

**Pull request merged**
